/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  StoryShareInterface,
  StoryShareInterfaceInterface,
} from "../StoryShareInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "username",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "profilePic",
        type: "bytes",
      },
    ],
    name: "createAuthor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_storyCID",
        type: "bytes",
      },
    ],
    name: "createStory",
    outputs: [
      {
        internalType: "contract Story",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "getAuthor",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "username",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "profilePicCID",
            type: "bytes",
          },
          {
            internalType: "uint8",
            name: "reputation",
            type: "uint8",
          },
        ],
        internalType: "struct SharedStructs.Author",
        name: "author",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_storyCID",
        type: "bytes",
      },
    ],
    name: "setFeaturedStoryCID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "reputationChange",
        type: "uint8",
      },
    ],
    name: "updateAuthorRep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class StoryShareInterface__factory {
  static readonly abi = _abi;
  static createInterface(): StoryShareInterfaceInterface {
    return new utils.Interface(_abi) as StoryShareInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StoryShareInterface {
    return new Contract(address, _abi, signerOrProvider) as StoryShareInterface;
  }
}
