/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace SharedStructs {
  export type AuthorStruct = {
    addr: PromiseOrValue<string>;
    username: PromiseOrValue<BytesLike>;
    profilePicCID: PromiseOrValue<BytesLike>;
    reputation: PromiseOrValue<BigNumberish>;
  };

  export type AuthorStructOutput = [string, string, string, number] & {
    addr: string;
    username: string;
    profilePicCID: string;
    reputation: number;
  };
}

export interface StoryShareInterface extends utils.Interface {
  functions: {
    "authors(address)": FunctionFragment;
    "createAuthor(address,bytes32,bytes)": FunctionFragment;
    "createStory(bytes)": FunctionFragment;
    "featuredStory()": FunctionFragment;
    "getAuthor(address)": FunctionFragment;
    "getStoryByCID(bytes)": FunctionFragment;
    "isFeaturePromoted()": FunctionFragment;
    "setFeaturedStoryCID(bytes)": FunctionFragment;
    "stories(bytes)": FunctionFragment;
    "updateAuthorRep(address,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authors"
      | "createAuthor"
      | "createStory"
      | "featuredStory"
      | "getAuthor"
      | "getStoryByCID"
      | "isFeaturePromoted"
      | "setFeaturedStoryCID"
      | "stories"
      | "updateAuthorRep"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authors",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuthor",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createStory",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "featuredStory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStoryByCID",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isFeaturePromoted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeaturedStoryCID",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "stories",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAuthorRep",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "authors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "featuredStory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuthor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStoryByCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFeaturePromoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeaturedStoryCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stories", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAuthorRep",
    data: BytesLike
  ): Result;

  events: {};
}

export interface StoryShare extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StoryShareInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number] & {
        addr: string;
        username: string;
        profilePicCID: string;
        reputation: number;
      }
    >;

    createAuthor(
      addr: PromiseOrValue<string>,
      username: PromiseOrValue<BytesLike>,
      profilePic: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createStory(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    featuredStory(overrides?: CallOverrides): Promise<[string]>;

    getAuthor(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [SharedStructs.AuthorStructOutput] & {
        author: SharedStructs.AuthorStructOutput;
      }
    >;

    getStoryByCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { story: string }>;

    isFeaturePromoted(overrides?: CallOverrides): Promise<[boolean]>;

    setFeaturedStoryCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stories(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    updateAuthorRep(
      addr: PromiseOrValue<string>,
      reputationChange: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  authors(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, number] & {
      addr: string;
      username: string;
      profilePicCID: string;
      reputation: number;
    }
  >;

  createAuthor(
    addr: PromiseOrValue<string>,
    username: PromiseOrValue<BytesLike>,
    profilePic: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createStory(
    _storyCID: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  featuredStory(overrides?: CallOverrides): Promise<string>;

  getAuthor(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<SharedStructs.AuthorStructOutput>;

  getStoryByCID(
    _storyCID: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  isFeaturePromoted(overrides?: CallOverrides): Promise<boolean>;

  setFeaturedStoryCID(
    _storyCID: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stories(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  updateAuthorRep(
    addr: PromiseOrValue<string>,
    reputationChange: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    authors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, number] & {
        addr: string;
        username: string;
        profilePicCID: string;
        reputation: number;
      }
    >;

    createAuthor(
      addr: PromiseOrValue<string>,
      username: PromiseOrValue<BytesLike>,
      profilePic: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    createStory(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    featuredStory(overrides?: CallOverrides): Promise<string>;

    getAuthor(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<SharedStructs.AuthorStructOutput>;

    getStoryByCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    isFeaturePromoted(overrides?: CallOverrides): Promise<boolean>;

    setFeaturedStoryCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    stories(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    updateAuthorRep(
      addr: PromiseOrValue<string>,
      reputationChange: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    authors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createAuthor(
      addr: PromiseOrValue<string>,
      username: PromiseOrValue<BytesLike>,
      profilePic: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createStory(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    featuredStory(overrides?: CallOverrides): Promise<BigNumber>;

    getAuthor(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStoryByCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFeaturePromoted(overrides?: CallOverrides): Promise<BigNumber>;

    setFeaturedStoryCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stories(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAuthorRep(
      addr: PromiseOrValue<string>,
      reputationChange: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createAuthor(
      addr: PromiseOrValue<string>,
      username: PromiseOrValue<BytesLike>,
      profilePic: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createStory(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    featuredStory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAuthor(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStoryByCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFeaturePromoted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFeaturedStoryCID(
      _storyCID: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stories(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAuthorRep(
      addr: PromiseOrValue<string>,
      reputationChange: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
