/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Story } from "./Story";
export type { StoryShare } from "./StoryShare";
export type { StoryShareInterface } from "./StoryShareInterface";
